### PR TITLE
Update 0.9.4 beta

### PR DESCRIPTION
**Pull request by Merinorus**
Hello!

The 0.9.4-beta has been published a few days ago. Your docker image is so convenient I would love it to have the latest update. Here is how I could build it.

You can run the image from here:
https://hub.docker.com/r/merinorus/docker-pgmodeler

It's the same as yours but the file is much larger, I'm not a Docker expert. Feel free to update your dockerhub image so I can delete mine.

Thank you for your work!

### CODE REVIEW

**Comment by apazga** [comment]
Hi!

Perfect, thanks! I just updated everything for the next version with the script I have. It's currently building the images in Docker Hub.
I'll check the other changes you have to include them too.

Thanks again!

**Review by apazga — APPROVED** [review]
Great!

**Comment by apazga** [comment]
Merged, thanks!

**Comment by Merinorus** [comment]
That was fast, thank you!
I also changed the run scripts (windows, linux, macos) but it might be confusing, I'm not sure if it was a great way to do it. Feel free to check this on my branch.

**Comment by apazga** [comment]
Hi @Merinorus!
Just updated it for 0.9.4-beta1. I also checked the additional changes you did.
Of course, make a pull request with MacOS changes, it would be nice to add that too.
Thanks!

**Comment by Merinorus** [comment]
Hey! Ok when I have some time I will review my modification and make a pull request!
Thank you

**Pull request merged**
